### ISSUE TITLE
Timeout Problem

### ISSUE THREAD

**Issue by MrJerB** [Azure/azure-diagnostics-tools#109] opened 2017-10-13 13:36 UTC
Trying this input for the first time. Upon config, the pipeline shows no activity and then produces this.
[error.txt](https://github.com/Azure/azure-diagnostics-tools/files/1382751/error.txt)

When shutting down the pipeline the following error also shows:
[error2.txt](https://github.com/Azure/azure-diagnostics-tools/files/1382765/error2.txt)

**Comment by xiaomi7732** [comment] 2017-10-16 16:35
@MrJerB, thanks for reporting the problem. The first error looks like the logstash can't create network connection to your azure-blob, could you please double check that?
Error 2 seems like a code defect - I'll put more investigation there and get more info back here.

**Comment by xiaomi7732** [comment] 2017-10-16 16:48
@MrJerB 
Error 2 is caused by a bug in the code and will be fixed along in PR #111.

**Comment by xiaomi7732** [comment] 2017-10-27 16:54
@MrJerB,
Any update?

**Comment by MrJerB** [comment] 2017-10-28 11:00
@xiaomi7732 Sorry for the inactivity, I am away from my machine for a short while. I'll check back and close the issue the soonest chance I get.

**Comment by xiaomi7732** [comment] 2017-10-30 16:14
@MrJerB ,
No problem at all. Please take your time. Let's know if there's anything we can do.

**Closed** 2017-11-26 08:55 UTC
Labels: logstash-input-azureblobs
