### ISSUE TITLE
logstash-input-azurewadtable is not reliably retrieving data for all VMs in a VM Scale Set

### ISSUE THREAD

**Issue by jstangroome** [Azure/azure-diagnostics-tools#23] opened 2016-07-25 04:02 UTC
I have a VM Scale Set with a minimum of two instances. These VMs run Linux: Ubuntu Trusty.

My Storage Account for diagnostics has Table Storage tables named `Linux*Ver2v0`, eg `LinuxCpuVer2v0`. I am using Logstash 2.3 and the `azurewadtable` input plugin to consume data in these tables.

It mostly works. Usually the input plugin is retrieving all data in the tables for all VMs in the Scale Set. However, it also often misses data for a particular VM and I have been able to determine why.

Take this scenario:
1. At 07:00:03 UTC, VM-A records a row to the table with PartitionKey `0000000000000000000___0636035580000000000` and TIMESTAMP `2016-07-08T07:00:00.000Z`.
2. At 07:00:06 UTC, the Logstash azurewadtable plugin queries the table, retrieves the newly inserted row and sets its `@last_timestamp` variable to the TIMESTAMP value `2016-07-08T07:00:00.000Z`.
3. At 07:00:08 UTC, VM-B records a row to the table, also with PartitionKey `0000000000000000000___0636035580000000000` and TIMESTAMP `2016-07-08T07:00:00.000Z` because partition keys and timestamps omit the seconds.
4. At 07:00:21 UTC, the Logstash azurewadtable plugin queries the table again filtered by partition keys exclusively greater than `0000000000000000000___0636035580000000000` and will therefore never retrieve the row for VM-B.

I have verified this behaviour by changing the line which assigns the TIMESTAMP field value to the `@last_timestamp` variable to subtract 60 seconds from the TIMESTAMP value. This causes rows from VM-A to be retrieved twice but will now also retrieve rows that have arrived late from VM-B.

This is not a good solution but it proves the problem.

**Comment by damiendurant** [comment] 2016-07-26 15:07
I confirm the same kind of behaviour on a 5 VMs Scaleset.

**Comment by EmFl** [comment] 2016-09-07 13:37
It seems I'm still missing a lot of data with the code from the pull request, wasn't able to pinpoint yet the root cause. Is anyone still experiencing this ?

**Comment by clguimanMSFT** [comment] 2017-09-20 17:11
@EmFl Can you please build and use the code in PR #98? This will cache query results and make sure there are no duplicates or missing data.

**Comment by clguimanMSFT** [comment] 2017-10-02 20:38
Fixed in version 0.9.12

**Closed by clguimanMSFT** 2017-10-02 20:38 UTC
Labels: logstash-input-azuretable
