### ISSUE TITLE
Wrong service-bus topics when using muliple azuretopicthreadable 

### ISSUE THREAD

**Issue by addp009** [Azure/azure-diagnostics-tools#113] opened 2017-10-25 19:07 UTC
When I have multiple azuretopicthreadable configured to consume multiple service buses, logstash tries to access the wrong bus and topics. It seems like the plugin variables are escaping scope? 

```@status=404>>, @uri=#<URI::HTTPS:0x53859121 URL:https://servicebus-b.servicebus.windows.net/topica/subscriptions/suba/messages/head?timeout=1>>, @uri: #<URI::HTTPS:0x53859121 URL:h*ttps://servicebus-b.servicebus.windows.net/topica/subscriptions/suba/messages/head*?timeout=1>, @type: "404">}```

```
azuretopicthreadable
{
	namespace => "servicebus-b"
	access_key_name => "rootManageSharedAccessKey"
	access_key => "KEYHERE"
	topic => "topicb"
	subscription => "subb"
	threads => 10
	thread_sleep_time => 10
}
	
azuretopicthreadable
{
	namespace => "servicebus-a"
	access_key_name => "rootManageSharedAccessKey"
	access_key => "KEYHERE"
	topic => "topica"
	subscription => "suba"
	threads => 10
	thread_sleep_time => 10
}

```

**Comment by xiaomi7732** [comment] 2017-10-27 16:58
@addp009 ,
I'll take an initial investigation. Please feel free to dive in to checkout what is going on. Update will be posted once there's progress.

**Comment by xiaomi7732** [comment] 2017-10-27 19:03
@addp009, Thanks for reporting this issue. It is confirmed. The root cause is in the ruby sdk linked above. Please feel free to follow up on that thread.

**Comment by xiaomi7732** [comment] 2017-11-20 17:50
Close this one since there's no action could be taken from azure-blob plugin side.

**Closed** 2017-11-20 17:50 UTC
Labels: external, logstash-input-azuretopic
