### ISSUE TITLE
logstash-input-azurewadtable is not reliably retrieving data

### ISSUE THREAD

**Issue by yzhang-myob** [Azure/azure-diagnostics-tools#71] opened 2017-03-25 10:31 UTC
Hello,
We have a classic table storage account to accept logs from class cloud service. A typical log entry in `WADLogsTable` would have partition key like '0636259969000000000'. So a query `PartitionKey gt '0636259968000000000' and PartitionKey lt '0636260301600000000'` will return correct data. However, when using **logstash-input-azurewadtable**, the actual query generated is: 

```
Query filter: (PartitionKey gt '0636259968000000000' and PartitionKey lt '0636260301600000000') or (PartitionKey gt '0000000000000000000___0636259968000000000' and PartitionKey lt '0000000000000000000___0636260301600000000') or (PartitionKey gt '0000000000000000001___0636259968000000000' and PartitionKey lt '0000000000000000001___0636260301600000000') or (PartitionKey gt '0000000000000000002___0636259968000000000' and PartitionKey lt '0000000000000000002___0636260301600000000') or (PartitionKey gt '0000000000000000003___0636259968000000000' and PartitionKey lt '0000000000000000003___0636260301600000000') or (PartitionKey gt '0000000000000000004___0636259968000000000' and PartitionKey lt '0000000000000000004___0636260301600000000') or (PartitionKey gt '0000000000000000005___0636259968000000000' and PartitionKey lt '0000000000000000005___0636260301600000000') or (PartitionKey gt '0000000000000000006___0636259968000000000' and PartitionKey lt '0000000000000000006___0636260301600000000') or (PartitionKey gt '0000000000000000007___0636259968000000000' and PartitionKey lt '0000000000000000007___0636260301600000000') or (PartitionKey gt '0000000000000000008___0636259968000000000' and PartitionKey lt '0000000000000000008___0636260301600000000') or (PartitionKey gt '0000000000000000009___0636259968000000000' and PartitionKey lt '0000000000000000009___0636260301600000000') or (PartitionKey gt '0000000000000000010___0636259968000000000' and PartitionKey lt '0000000000000000010___0636260301600000000') or (PartitionKey gt '0000000000000000011___0636259968000000000' and PartitionKey lt '0000000000000000011___0636260301600000000') or (PartitionKey gt '0000000000000000012___0636259968000000000' and PartitionKey lt '0000000000000000012___0636260301600000000') or (PartitionKey gt '0000000000000000013___0636259968000000000' and PartitionKey lt '0000000000000000013___0636260301600000000') or (PartitionKey gt '0000000000000000014___0636259968000000000' and PartitionKey lt '0000000000000000014___0636260301600000000') or (PartitionKey gt '0000000000000000015___0636259968000000000' and PartitionKey lt '0000000000000000015___0636260301600000000') or (PartitionKey gt '0000000000000000016___0636259968000000000' and PartitionKey lt '0000000000000000016___0636260301600000000') or (PartitionKey gt '0000000000000000017___0636259968000000000' and PartitionKey lt '0000000000000000017___0636260301600000000') or (PartitionKey gt '0000000000000000018___0636259968000000000' and PartitionKey lt '0000000000000000018___0636260301600000000') or (PartitionKey gt '0000000000000000019___0636259968000000000' and PartitionKey lt '0000000000000000019___0636260301600000000') or (PartitionKey gt '0000000000000000020___0636259968000000000' and PartitionKey lt '0000000000000000020___0636260301600000000') or (PartitionKey gt '0000000000000000021___0636259968000000000' and PartitionKey lt '0000000000000000021___0636260301600000000') or (PartitionKey gt '0000000000000000022___0636259968000000000' and PartitionKey lt '0000000000000000022___0636260301600000000') or (PartitionKey gt '0000000000000000023___0636259968000000000' and PartitionKey lt '0000000000000000023___0636260301600000000') or (PartitionKey gt '0000000000000000024___0636259968000000000' and PartitionKey lt '0000000000000000024___0636260301600000000') or (PartitionKey gt '0000000000000000025___0636259968000000000' and PartitionKey lt '0000000000000000025___0636260301600000000') or (PartitionKey gt '0000000000000000026___0636259968000000000' and PartitionKey lt '0000000000000000026___0636260301600000000') or (PartitionKey gt '0000000000000000027___0636259968000000000' and PartitionKey lt '0000000000000000027___0636260301600000000') or (PartitionKey gt '0000000000000000028___0636259968000000000' and PartitionKey lt '0000000000000000028___0636260301600000000') or (PartitionKey gt '0000000000000000029___0636259968000000000' and PartitionKey lt '0000000000000000029___0636260301600000000') or (PartitionKey gt '0000000000000000030___0636259968000000000' and PartitionKey lt '0000000000000000030___0636260301600000000') or (PartitionKey gt '0000000000000000031___0636259968000000000' and PartitionKey lt '0000000000000000031___0636260301600000000') or (PartitionKey gt '0000000000000000032___0636259968000000000' and PartitionKey lt '0000000000000000032___0636260301600000000') or (PartitionKey gt '0000000000000000033___0636259968000000000' and PartitionKey lt '0000000000000000033___0636260301600000000') or (PartitionKey gt '0000000000000000034___0636259968000000000' and PartitionKey lt '0000000000000000034___0636260301600000000') or (PartitionKey gt '0000000000000000035___0636259968000000000' and PartitionKey lt '0000000000000000035___0636260301600000000') or (PartitionKey gt '0000000000000000036___0636259968000000000' and PartitionKey lt '0000000000000000036___0636260301600000000') or (PartitionKey gt '0000000000000000037___0636259968000000000' and PartitionKey lt '0000000000000000037___0636260301600000000') or (PartitionKey gt '0000000000000000038___0636259968000000000' and PartitionKey lt '0000000000000000038___0636260301600000000') or (PartitionKey gt '0000000000000000039___0636259968000000000' and PartitionKey lt '0000000000000000039___0636260301600000000') or (PartitionKey gt '0000000000000000040___0636259968000000000' and PartitionKey lt '0000000000000000040___0636260301600000000') or (PartitionKey gt '0000000000000000041___0636259968000000000' and PartitionKey lt '0000000000000000041___0636260301600000000') or (PartitionKey gt '0000000000000000042___0636259968000000000' and PartitionKey lt '0000000000000000042___0636260301600000000') or (PartitionKey gt '0000000000000000043___0636259968000000000' and PartitionKey lt '0000000000000000043___0636260301600000000') or (PartitionKey gt '0000000000000000044___0636259968000000000' and PartitionKey lt '0000000000000000044___0636260301600000000') or (PartitionKey gt '0000000000000000045___0636259968000000000' and PartitionKey lt '0000000000000000045___0636260301600000000') or (PartitionKey gt '0000000000000000046___0636259968000000000' and PartitionKey lt '0000000000000000046___0636260301600000000') or (PartitionKey gt '0000000000000000047___0636259968000000000' and PartitionKey lt '0000000000000000047___0636260301600000000') or (PartitionKey gt '0000000000000000048___0636259968000000000' and PartitionKey lt '0000000000000000048___0636260301600000000') or (PartitionKey gt '0000000000000000049___0636259968000000000' and PartitionKey lt '0000000000000000049___0636260301600000000') or (PartitionKey gt '0000000000000000050___0636259968000000000' and PartitionKey lt '0000000000000000050___0636260301600000000') or (PartitionKey gt '0000000000000000051___0636259968000000000' and PartitionKey lt '0000000000000000051___0636260301600000000') or (PartitionKey gt '0000000000000000052___0636259968000000000' and PartitionKey lt '0000000000000000052___0636260301600000000') or (PartitionKey gt '0000000000000000053___0636259968000000000' and PartitionKey lt '0000000000000000053___0636260301600000000') or (PartitionKey gt '0000000000000000054___0636259968000000000' and PartitionKey lt '0000000000000000054___0636260301600000000') or (PartitionKey gt '0000000000000000055___0636259968000000000' and PartitionKey lt '0000000000000000055___0636260301600000000') or (PartitionKey gt '0000000000000000056___0636259968000000000' and PartitionKey lt '0000000000000000056___0636260301600000000') or (PartitionKey gt '0000000000000000057___0636259968000000000' and PartitionKey lt '0000000000000000057___0636260301600000000') or (PartitionKey gt '0000000000000000058___0636259968000000000' and PartitionKey lt '0000000000000000058___0636260301600000000') or (PartitionKey gt '0000000000000000059___0636259968000000000' and PartitionKey lt '0000000000000000059___0636260301600000000') or (PartitionKey gt '0000000000000000060___0636259968000000000' and PartitionKey lt '0000000000000000060___0636260301600000000') or (PartitionKey gt '0000000000000000061___0636259968000000000' and PartitionKey lt '0000000000000000061___0636260301600000000') or (PartitionKey gt '0000000000000000062___0636259968000000000' and PartitionKey lt '0000000000000000062___0636260301600000000') or (PartitionKey gt '0000000000000000063___0636259968000000000' and PartitionKey lt '0000000000000000063___0636260301600000000') or (PartitionKey gt '0000000000000000064___0636259968000000000' and PartitionKey lt '0000000000000000064___0636260301600000000') or (PartitionKey gt '0000000000000000065___0636259968000000000' and PartitionKey lt '0000000000000000065___0636260301600000000') or (PartitionKey gt '0000000000000000066___0636259968000000000' and PartitionKey lt '0000000000000000066___0636260301600000000') or (PartitionKey gt '0000000000000000067___0636259968000000000' and PartitionKey lt '0000000000000000067___0636260301600000000') or (PartitionKey gt '0000000000000000068___0636259968000000000' and PartitionKey lt '0000000000000000068___0636260301600000000') or (PartitionKey gt '0000000000000000069___0636259968000000000' and PartitionKey lt '0000000000000000069___0636260301600000000') or (PartitionKey gt '0000000000000000070___0636259968000000000' and PartitionKey lt '0000000000000000070___0636260301600000000') or (PartitionKey gt '0000000000000000071___0636259968000000000' and PartitionKey lt '0000000000000000071___0636260301600000000') or (PartitionKey gt '0000000000000000072___0636259968000000000' and PartitionKey lt '0000000000000000072___0636260301600000000') or (PartitionKey gt '0000000000000000073___0636259968000000000' and PartitionKey lt '0000000000000000073___0636260301600000000') or (PartitionKey gt '0000000000000000074___0636259968000000000' and PartitionKey lt '0000000000000000074___0636260301600000000') or (PartitionKey gt '0000000000000000075___0636259968000000000' and PartitionKey lt '0000000000000000075___0636260301600000000') or (PartitionKey gt '0000000000000000076___0636259968000000000' and PartitionKey lt '0000000000000000076___0636260301600000000') or (PartitionKey gt '0000000000000000077___0636259968000000000' and PartitionKey lt '0000000000000000077___0636260301600000000') or (PartitionKey gt '0000000000000000078___0636259968000000000' and PartitionKey lt '0000000000000000078___0636260301600000000') or (PartitionKey gt '0000000000000000079___0636259968000000000' and PartitionKey lt '0000000000000000079___0636260301600000000') or (PartitionKey gt '0000000000000000080___0636259968000000000' and PartitionKey lt '0000000000000000080___0636260301600000000') or (PartitionKey gt '0000000000000000081___0636259968000000000' and PartitionKey lt '0000000000000000081___0636260301600000000') or (PartitionKey gt '0000000000000000082___0636259968000000000' and PartitionKey lt '0000000000000000082___0636260301600000000') or (PartitionKey gt '0000000000000000083___0636259968000000000' and PartitionKey lt '0000000000000000083___0636260301600000000') or (PartitionKey gt '0000000000000000084___0636259968000000000' and PartitionKey lt '0000000000000000084___0636260301600000000') or (PartitionKey gt '0000000000000000085___0636259968000000000' and PartitionKey lt '0000000000000000085___0636260301600000000') or (PartitionKey gt '0000000000000000086___0636259968000000000' and PartitionKey lt '0000000000000000086___0636260301600000000') or (PartitionKey gt '0000000000000000087___0636259968000000000' and PartitionKey lt '0000000000000000087___0636260301600000000') or (PartitionKey gt '0000000000000000088___0636259968000000000' and PartitionKey lt '0000000000000000088___0636260301600000000') or (PartitionKey gt '0000000000000000089___0636259968000000000' and PartitionKey lt '0000000000000000089___0636260301600000000') or (PartitionKey gt '0000000000000000090___0636259968000000000' and PartitionKey lt '0000000000000000090___0636260301600000000') or (PartitionKey gt '0000000000000000091___0636259968000000000' and PartitionKey lt '0000000000000000091___0636260301600000000') or (PartitionKey gt '0000000000000000092___0636259968000000000' and PartitionKey lt '0000000000000000092___0636260301600000000') or (PartitionKey gt '0000000000000000093___0636259968000000000' and PartitionKey lt '0000000000000000093___0636260301600000000') or (PartitionKey gt '0000000000000000094___0636259968000000000' and PartitionKey lt '0000000000000000094___0636260301600000000') or (PartitionKey gt '0000000000000000095___0636259968000000000' and PartitionKey lt '0000000000000000095___0636260301600000000') or (PartitionKey gt '0000000000000000096___0636259968000000000' and PartitionKey lt '0000000000000000096___0636260301600000000') or (PartitionKey gt '0000000000000000097___0636259968000000000' and PartitionKey lt '0000000000000000097___0636260301600000000') or (PartitionKey gt '0000000000000000098___0636259968000000000' and PartitionKey lt '0000000000000000098___0636260301600000000') or (PartitionKey gt '0000000000000000099___0636259968000000000' and PartitionKey lt '0000000000000000099___0636260301600000000')
```

which does not work. It return empty results set.

**Comment by EmFl** [comment] 2017-03-27 08:00
I'm having issues with this as well, ended up commenting out the loop in the plugin, however I can't fetch any data for services using medium or large diagnostic event volume config

**Comment by yzhang-myob** [comment] 2017-03-27 08:19
Ah, cool. No problem. I probably fork, modify and build one for my purpose then.

**Comment by clguimanMSFT** [comment] 2017-09-15 21:48
@EmFl @yzhang-myob I can't reproduce the issue. The query should work as it is, because the second part is doesn't add restrictions to the query, it just extends the possible set of results.
Can one of you try to reproduce the problem and share the query and data?

**Comment by brahmnes** [comment] 2018-02-27 17:27
As @clguimanMSFT has mentioned, the query checks both the formats:
0636259969000000000
0000000000000000001_0636259969000000000

This line of code is the part of the filter accepting the first format
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azurewadtable/lib/logstash/inputs/azurewadtable.rb#L90

Closing this issue unless more people are seeing this issue.

**Closed by brahmnes** 2018-02-27 17:27 UTC
Labels: logstash-input-azuretable
