### ISSUE TITLE
java.lang.NegativeArraySizeException on blob plugin

### ISSUE THREAD

**Issue by paulpc** [Azure/azure-diagnostics-tools#70] opened 2017-03-15 20:47 UTC
20:34:05.581 [[main]<azureblob] ERROR logstash.inputs.azureblob - Oh My, An error occurred. {:exception=>java.lang.NegativeArraySizeException}

I have some JSON files in blob ranging in size between 1 and 1.7 GB. After some troubleshooting of JVM size and VM size, I now get this error.

**Comment by brahmnes** [comment] 2017-03-28 19:25
Do you believe it's due to the size of the blob?
Looking at https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/blob/blob.rb, it looks like it may be possible to add an option to get the blob piece by piece. Perhaps you can modify the plugin to see if that helps?

**Comment by xiaomi7732** [comment] 2017-07-31 18:37
@paulpc,
This looks like a bug lying in azure-storage sdk in terms of bring down big blob. Is it possible to share us a copy of your blob?

**Comment by paulpc** [comment] 2017-07-31 23:08
Let me see if I can do it on a sanitized copy of the data

**Comment by xiaomi7732** [comment] 2017-07-31 23:26
@paulpc, thank you in advance!

**Comment by xiaomi7732** [comment] 2017-08-31 05:10
@paulpc,
How is things going up there?

**Comment by xiaomi7732** [comment] 2017-09-19 20:52
I can repro this issue now by having a huge log file (> 1.5G). It failed to load the whole file by calling into storage sdk to get the blob.
@clguimanMSFT, if time permits, could you please take a look will paging loading the blob solving the issue?

**Comment by clguimanMSFT** [comment] 2017-10-03 19:33
The issue should be fixed in v.0.9.12
@paulpc can you please check with the latest version?

**Comment by brahmnes** [comment] 2017-11-03 22:58
Closing since the issue is now fixed

**Closed by brahmnes** 2017-11-03 22:58 UTC
Labels: logstash-input-azureblobs
